### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by demarant** [eea/geonetwork-eea#14]
**Describe the bug**
github security scan has discovered a few security issues that should be looked up.

**Expected behavior**
it is EEA's security policy to not have any critical security issues in the code. Please review and see if actions are needed to mitigate the issues, for example patching or upgrading the libraries in use.

**Screenshots**
![geonetwork-securityissues](https://user-images.githubusercontent.com/320440/75765569-00be8f00-5d40-11ea-96f4-ff9f7910435e.png)

**Comment by fxprunayre** [comment]
The one for Lucene does not apply in the context of GeoNetwork.
A couple of others covered by https://github.com/geonetwork/core-geonetwork/pull/4505.

**Comment by fxprunayre** [comment]
Most of them should have been addressed in https://github.com/eea/geonetwork-eea/tree/eea-4.0.x.

Related GeoNetwork issues:
https://github.com/geonetwork/core-geonetwork/pull/4834
https://github.com/geonetwork/core-geonetwork/pull/4505
https://github.com/geonetwork/core-geonetwork/pull/4827

Can you change the default branch to the `eea-4.0.x` which will be the next version deployed on test from now so that github analyze that branch? Thanks
